### ISSUE TITLE
PandoraPFA correction xml tag mismatch

### ISSUE THREAD

**Issue by rete** [iLCSoft/ILDConfig#14]
I noticed in the main Pandora settings file, the following : 
[PandoraSettingsDefault.xml](https://github.com/iLCSoft/ILDConfig/blob/master/StandardConfig/lcgeo_current/PandoraSettingsDefault.xml#L10)
with "HadronicEnergyCorrectionPlugins" and in the SDHCAL Pandora settings file, the following : 
[PandoraSettingsDefault_sdhcal.xml](https://github.com/iLCSoft/ILDConfig/blob/master/StandardConfig/lcgeo_current/PandoraSettingsDefault_sdhcal.xml#L9)
with "HadronicEnergyCorrectionFunctions".

Is it due to different PandoraPFA version use or a mistake/missing update from somebody ?

**Comment by rete** [comment]
pinging @libo929 for checking

**Comment by rete** [comment]
@libo929 Should have I to close this issue ?

**Comment by libo929** [comment]
@rete "HadronicEnergyCorrectionFunctions" is oringinated from old revision of setting file. We should correct it for the new Pandora.

**Comment by rete** [comment]
By comparing PandoraSettingsDefault.xml and PandoraSettingsDefault_sdhcal.xml, I also see many differences in the algorithms themselves. I'm not sure what to modify, and even more, how to test the changes.

@libo929 Can you walk through both setting files and update the sdhcal one ?

**Comment by rete** [comment]
@libo929 Any news ?

**Comment by libo929** [comment]
I have tried to use PandoraSettingsDefault.xml for SDHCAL:
hit energy is from SimDigital with parameters of linear energy function;
without Software Compensation, currently it doesn't work for SDHCAL

**Comment by libo929** [comment]
@rete

**Comment by rete** [comment]
Then my question is : Should the Pandora energy correction be the only difference in the settings ? 
If so, I can simply copy paste the current PandoraSettingsDefault.xml content in the sdhcal version and change the energy correction.

I have a second question : do you have any idea of which correction to apply in Pandora for SDHCAL ? 
The current one in the sdhcal file is only CleanClusters which acts on the Ecal hits only (as far as I know ...)

**Comment by libo929** [comment]
Hello Remi,
1) I think so. For SDHCAL, I checked it with single particle (pi+), the result seems reasonable.
2) I have no idea. Probably we can use the quadratic formula, which however need to be implemented in Pandora ?
