### ISSUE TITLE
hybrid ecal hit digitisation

### ISSUE THREAD

**Issue by danieljeans** [iLCSoft/ILDConfig#16]
For the hybrid ecal reconstruction, MergeCollections is used to merge si-ecal collections in even and odd layers; this merged collection is then passed to the digitisation step.
The RealisticCaloDigi.cc processor uses the CellIDEncoding: `col->getParameters().getStringVal(LCIO::CellIDEncoding);`

However, the merged collection keeps the encodings of the original input collections in a way not known about to the digitisation processor:
```
 parameter ECalBarrelSiHitsEven_CellIDEncoding [string]: system:0:5,module:5:3,stave:8:4,tower:12:4,layer:16:6,wafer:22:6,slice:28:4,cellX:32:-16,cellY:48:-16, 
 parameter ECalBarrelSiHitsOdd_CellIDEncoding [string]: system:0:5,module:5:3,stave:8:4,tower:12:4,layer:16:6,wafer:22:6,slice:28:4,cellX:32:-16,cellY:48:-16, 
```
Am I missing something, or do we need a work-around?

**Comment by gaede** [comment]
I had addressed this in https://github.com/iLCSoft/LCTuple/pull/2 - but just after making the v01-19-04 iLCSoft release. So you can update the LCTuple version to v01-09 for now...
