### ISSUE TITLE
Add a test for simulation and reconstruction

### ISSUE THREAD

**Issue by andresailer** [iLCSoft/ILDConfig#2]
Maybe you could add a test to ILDConfig to run simulation and reconstruction, similar to
https://github.com/iLCSoft/CLICPerformance/blob/master/Tests/CMakeLists.txt

Would allow easier testing, and make sure that the steering files are not broken

**Comment by gaede** [comment]
Good idea - will have a look.

**Comment by rete** [comment]
Also, we should maybe prepare small aa_lowpt and ee pair bg files (5 events) to test the reco chain with the overlay ON.

**Comment by rete** [comment]
Done in #62
