### ISSUE TITLE
ddsim not working with local copy of detector model

### ISSUE THREAD

**Issue by luisaleperez** [iLCSoft/ILDConfig#3]
Hello all,

I am in charge of performing studies of machine induced backgrounds from pairs processes. I wanted to launch a pre-production in to study the effect of the anti-DID on these backgrounds but I got a little problem. Maybe the solution is very simple but I don't manage to find it by myself. 

I just got the HEAD of ILDConfig by doing,

>$ git clone https://github.com/iLCSoft/ILDConfig.git
>$ cd ILDConfig/StandardConfig/lcgeo_current
>$ source /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/HEAD-2017-03-24/init_ilcsoft.sh

I wanted to run the a slight modification of the detector model ILD_o1_v05.xml in 

$lcgeo_DIR/ILD/compact/ILD_o1_v05/ILD_o1_v05.xml

in which I modify the relative strength of the anti-DID field with respect to the solenoidal field. For that I copied the ILD_o1_v05.xml file in my ILDConfig/StandardConfig/lcgeo_current directoty and did,

ddsim  --inputFiles ./pairs_file.pairs --outputFile=./pairs_1evt.slcio --compactFile ILD_o1_v05.xml  --steeringFile=./ddsim_steer_GuineaPig.py

where pairs_file.pairs is an input file from GuineaPig generator, and ddsim_steer_GuineaPig.py is an steering file that I created for the case of pairs backgrounds. If I do this I get the following error,

XMLLoader        INFO  +++ Processing XML file: file:ILD_o1_v05.xml
DocumentHandler  INFO  +++ Loading document URI: file:ILD_o1_v05.xml [Resolved:'ILD_o1_v05.xml']
DocumentHandler  INFO  +++ Document file:ILD_o1_v05.xml succesfully parsed with TinyXML .....
DocumentHandler  INFO  +++ Loading document URI: /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/HEAD-2017-03-24/DD4hep/HEAD/DDDetectors/compact/detector_types.xml [Resolved:'/afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/HEAD-2017-03-24/DD4hep/HEAD/DDDetectors/compact/detector_types.xml']
DocumentHandler  INFO  +++ Document /afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/HEAD-2017-03-24/DD4hep/HEAD/DDDetectors/compact/detector_types.xml succesfully parsed with TinyXML .....
DocumentHandler  INFO  +++ Loading document URI: model_parameters_ILD_o1_v05.xml [Resolved:'model_parameters_ILD_o1_v05.xml']
DocumentHandler  FATAL +++ Error (TinyXML) parsing XML document:model_parameters_ILD_o1_v05.xml [model_parameters_ILD_o1_v05.xml]
DocumentHandler  FATAL +++ Error (TinyXML) XML parsing error:Failed to open file
DocumentHandler  FATAL +++ Document:model_parameters_ILD_o1_v05.xml Location Line:0 Column:0
DD4hep:XML       ERROR ++ file:model_parameters_ILD_o1_v05.xml error:Failed to open file
DocumentHandler  ERROR +++ Exception (TinyXML): parse(path):DD4hep:XML: ++ file:model_parameters_ILD_o1_v05.xml error:Failed to open file
Traceback (most recent call last):
  File "/afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/HEAD-2017-03-24/lcgeo/HEAD/bin/ddsim", line 16, in <module>
    RUNNER.run()
  File "/afs/desy.de/project/ilcsoft/sw/x86_64_gcc49_sl6/HEAD-2017-03-24/lcgeo/HEAD/lib/python/DDSim/DD4hepSimulation.py", line 275, in run
    kernel.loadGeometry("file:"+ self.compactFile )
Exception: void DD4hep::Simulation::Geant4Kernel::loadGeometry(const string& compact_file) =>
    Document::root: Invalid handle!
DD4hep: Error interpreting XML nodes of type <include/>
DD4hep: Error interpreting XML nodes of type <define/>
DD4hep: while parsing file:ILD_o1_v05.xml
DD4hep: with plugin:DD4hepXMLLoader (C++ exception of type runtime_error)

But if stead I use the detector model file directly from the $lcgeo_DIR directory as follows

ddsim  --inputFiles ./pairs_file.pairs --outputFile=./pairs_1evt.slcio --compactFile $lcgeo_DIR/ILD/compact/ILD_o1_v05/ILD_o1_v05.xml  --steeringFile=./ddsim_steer_GuineaPig.py

it works!

So, my question is, if I want to use a modified version of the ILD_o1_v05.xml file do I need to get the corresponding version of lcgeo and modify the file inside the ILD/compact/ILD_o1_v05/ or there is a simpler solution?

Many thanks,

  Alejandro

**Comment by gaede** [comment]
Hi Alejandro,

for the lcgeo compact description you always need the complete directory, as it contains several xml files  that are loaded. So all you need is to copy the directory, e.g. $lcgeo_DIRILD/compact/ILD_o1_v05 somewhere and modify the files inside this directory accordingly.

Cheers, Frank.

**Comment by gaede** [comment]
PS: to run on the NAF batch system, you have to copy the directory of course to a path that is visible on the batch system, e.g. in /afs/desy.de/... or on you sonas/dust directory
