### ISSUE TITLE
Problem with splitting event

### ISSUE THREAD

**Issue by luisaleperez** [iLCSoft/ILDConfig#4]
Hello all,

As I already said, I am working on the simulations of pairs backgrounds. The inputs files from the GuinaPig generator corresponds to the primaries generated by a single bunch-crossing. These files contains around 200k particles. In order to reduce stress on the memory I would like to split all these 200k particles into several events with 1000 particles (ending-up with ~200 events).

I did a simple test with a GuineaPig file containing only 2216 primaries. The steering file running ddsim is here below,

[ddsim_steer_GuineaPig.py.txt](https://github.com/iLCSoft/ILDConfig/files/909755/ddsim_steer_GuineaPig.py.txt)

As you can see, I set

SIM.numberOfEvents = 3
SIM.skipNEvents = 1000

But I get the following error,

GenerationInit   INFO  +++ Initializing event 1. Within run:0 event 1.
EventReaderGuineaPig::setParameters INFO   --- Will read all particles in pairs file into one event
EventReaderGuineaPig::moveToEvent ERROR  --- Cannot skip to event 1000 in GuineaPig file without parameter 'ParticlesPerEvent' being set !

-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : Geant4InputAction[GuineaPig4]: Event 1000 Error when moving to event - may be end of file.
      issued by : GuineaPig4 [DD4hep::Simulation::Geant4InputAction]
*** Geant4Action:: Error when reading file Geant4EventReaderGuineaPig|./E500-TDR_ws.PBeamstr-pairs.GGuineaPig-v1-4-4.I230000.0001_TEST_1percent.pairs
*** Run Must Be Aborted ***
-------- EEEE -------- G4Exception-END --------- EEEE -------

Geant4InteractionVertexBoost INFO  +++ No interaction of type 4 present.
ParticleHandler  INFO  +++ Event 1000 Begin event action. Access event related information.
LcioOutput       WARN  +++ [Event:1000] No valid MC truth info present. Is a Particle handler installed ?
LcioOutput       ERROR +++ [Event:1000] Exception while saving event:lcio::DataNotAvailableException: LCEventImpl::getCollection: collection not in event:MCParticle
LcioOutput       ERROR +++ [Event:1000] Exception while saving event:lcio::DataNotAvailableException: LCEventImpl::getCollection: collection not in event:MCParticle
Geant4Kernel     FATAL +++ Exception while simulating:lcio::DataNotAvailableException: LCEventImpl::getCollection: collection not in event:MCParticle
Geant4Kernel     INFO  ++ Terminate Geant4 and delete associated actions.

If I do

SIM.numberOfEvents = 1
SIM.skipNEvents = 0

It works. But when I send a jobs with the full input pairs file with ~200k particles the jobs gets killed as the system puts in a single event 200k particles.

I also tried to set in the steering file the variable ParticlesPerEvent as the above error message says. It did as follows,

SIM.numberOfEvents = 3
SIM.ParticlesPerEvent=1000

But I it doesn't work. The systems puts all the 2216 particles in the 1st event and then I get the following error message,

GenerationInit   INFO  +++ Initializing event 2. Within run:0 event 2.

-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : Geant4InputAction[GuineaPig4]: Event 1 Error when moving to event - may be end of file.
      issued by : GuineaPig4 [DD4hep::Simulation::Geant4InputAction]
*** Geant4Action:: Error when reading file Geant4EventReaderGuineaPig|./E500-TDR_ws.PBeamstr-pairs.GGuineaPig-v1-4-4.I230000.0001_TEST_1percent.pairs
*** Run Must Be Aborted ***
-------- EEEE -------- G4Exception-END --------- EEEE -------

Geant4InteractionVertexBoost INFO  +++ No interaction of type 4 present.
ParticleHandler  INFO  +++ Event 1 Begin event action. Access event related information.
LcioOutput       WARN  +++ [Event:1] No valid MC truth info present. Is a Particle handler installed ?
LcioOutput       ERROR +++ [Event:1] Exception while saving event:lcio::DataNotAvailableException: LCEventImpl::getCollection: collection not in event:MCParticle
LcioOutput       ERROR +++ [Event:1] Exception while saving event:lcio::DataNotAvailableException: LCEventImpl::getCollection: collection not in event:MCParticle
Geant4Kernel     FATAL +++ Exception while simulating:lcio::DataNotAvailableException: LCEventImpl::getCollection: collection not in event:MCParticle
Geant4Kernel     INFO  ++ Terminate Geant4 and delete associated actions.

Any idea what I am doing wrong?

Many thanks,

  Alejandro

**Comment by gaede** [comment]
@luisaleperez you have to set:
```
SIM.guineapig.particlesPerEvent=3
```
to set the number of particles per event to be used with GuineaPig files.
You can always find out the options with:
```
ddsim --help
```

**Comment by luisaleperez** [comment]
Hi all,

It works now!  But you have to be very careful to set properly the values of guineapig.particlesPerEvent and the corresponding number of events. For example, if you have 223456 primaries in your GuinaPig and you set guineapig.particlesPerEvent=1000, then you need to set numberOfEvents=224 in order to fully simulate the GuinaPig input file.

Many thanks for the advise.

  Alejandro
