### ISSUE TITLE
 MarlinStdReco.xml

### ISSUE THREAD

**Issue by TiborILD** [iLCSoft/ILDConfig#44]
Hi Remi,
  I have 2 questions:
1.  Is the current MarliStdReco.xml file to be used to run MarlinReco in v01-19-05 ? 
  It fails, because the same DetectorModel name is used for lcgeo and for Calibration part, although
  they have different names  (in Calibration there is introduced another variable "option?  -  o1, o2 ...o5").
     Seems that you need 2 different names for lcgeo resp. Calibration detector models, something like ?

   "DetectorModel" value="ILD_l4_v02" 
   "CalibrationDetectorModel" value="ILD_L4_o2_v02" 

 2. Is the current release v01-19-05 foreseen to run MarlinReco also for Videau detector models like 
     ILD_l2_v02, ILD_s2_v02 (ILD_l6_v02,ILD_s6_v02)  ?
     One issue to be fixed is the hardwired  hybrid "inputHitCollections" parameter name for SDHCAL 
    in SDHcalDigi.xml. 
  <parameter name="inputHitCollections" type="StringVec" lcioInType="SimCalorimeterHit"> HCalBarrelRPCHits HCalEndcapRPCHits HCalECRingRPCHits </parameter>
   But even doing this, doesn't help to reconstruct from default "inputHitCollections" , i.e.
  from  "HcalBarrelRegCollections HcalEndcapsCollections HcalEndcapRingCollection "

**Comment by TiborILD** [comment]
Hi Remi,
  I have 2 questions:
1.  Is the current MarliStdReco.xml file to be used to run MarlinReco in v01-19-05 ? 
  It fails, because the same DetectorModel name is used for lcgeo and for Calibration part, although
  they have different names  (in Calibration there is introduced another variable "option?  -  o1, o2 ...o5").
     Seems that you need 2 different names for lcgeo resp. Calibration detector models, something like ?
   <constant name="DetectorModel" value="ILD_l4_v02" />
   <constant name="CalibrationDetectorModel" value="ILD_L4_o2_v02" />

 2. Is the current release v01-19-05 foreseen to run MarlinReco also for Videau detector models like 
     ILD_l2_v02, ILD_s2_v02 (ILD_l6_v02,ILD_s6_v02)  ?
     One issue to be fixed is the hardwired  hybrid "inputHitCollections" parameter name for SDHCAL 
    in SDHcalDigi.xml. 
  <parameter name="inputHitCollections" type="StringVec" lcioInType="SimCalorimeterHit"> HCalBarrelRPCHits HCalEndcapRPCHits HCalECRingRPCHits </parameter>
   But even doing this, doesn't help to reconstruct from default "inputHitCollections" , i.e.
  from  "HcalBarrelRegCollections HcalEndcapsCollections HcalEndcapRingCollection "

**Comment by rete** [comment]
Hi Tibor,

for the DetectorModel key in the MarlinStdReco.xml, it always has to be a model with the option set inside, e.g **NOT** *ILD_l4_v02* but *ILD_l4_o1_v02*, even if you simulated events with detector model ILD_l4_v02. The current supported models are listed in the Calibration directory. If you want to add on more (e.g ILD_l6_v02), create a new calibration file that has the most similar geometry, and give the same name as your detector model. For example for the model ILD_l2_v02, copy Calibration_ILD_l4_o2_v02.xml and and create a new one called Calibration_ILD_l2_v02.xml.

For your second point, I don't understand the problem. The output collections after simulation with SDHCal are HCalBarrelRPCHits HCalEndcapRPCHits HCalECRingRPCHits. The output collections after digitization (HcalBarrelCollectionRec HcalEndcapsCollectionRec HcalEndcapRingCollectionRec) need to have the same name has the AHcal ones to ensure the reconstruction takes the correct reconstructed hits, e.g, for PandoraPFA.

**Comment by rete** [comment]
@TiborILD Is your problem solved ?

**Comment by TiborILD** [comment]
1. yes, I figured it out how to do it.  But why the standard (non hybrid) models are not supported ? 

2.  output collections after simulation with SDHCAL called HCal.....RPCHits hits were introduced  only with the hybrid models.  In original, classical or standard models (ILD_l2(s2), l6(s6) the simulation output is called  "HcalBarrelRegCollections HcalEndcapsCollections HcalEndcapRingCollection ".
    So this makes the life more complicated. 
  To simplify the life, we should probably rename the simulation output collections from SDHCAL to the same name as in hybrid model (i.e. Hcal....RPCHits)  ?
   Is there any other place in the soft (besides SDHCAL digitizer) where the simulation output collections are used and the name change could create other problems?

**Comment by rete** [comment]
1. Because we don't have calibration constants and these models are not used for the production.

2. I think it is a good idea to have one set of collection names for all the SDHCAL detector in all simulation models. It is already the case for AHCal. Except in the digitizer, I don't think the sim hits collections are used. I took care of setting the same name as for AHcal for the reconstructed hits for the steps after reconstruction. The code was tested and the "normal" reconstructed collections such as PFOs, were populated. Do not hesitate to create a PR if you see something inconsistent in the steering files.

**Comment by rete** [comment]
@TiborILD Should we close this issue ?

**Comment by rete** [comment]
@gaede Can you close this issue please ?
