### ISSUE TITLE
Update calibration for production release

### ISSUE THREAD

**Issue by rete** [iLCSoft/ILDConfig#73]
The energy calibration constants have to be updated for the final production release (by running LCCalibration).

**Comment by rete** [comment]
@gaede Should we make a new tag without these updates, calibrate the energy constants and make them available for the final release ? Or should we run the calibration before making the next incoming tag ?

**Comment by gaede** [comment]
Let's make one tag w/ the old constants - then we can still update and make a patch tag....

**Comment by rete** [comment]
Ok. I keep this issue opened till the constants are there

**Comment by rete** [comment]
Closing as superseded by #75
