### ISSUE TITLE
Readiness for production

### ISSUE THREAD

**Issue by rete** [iLCSoft/ILDConfig#75]
@gaede @shaojunlu @danieljeans 
I post this issue as a central post for the things we need to check before going to the final production.
Here is the proposal list:

- [x] JER/JES (uds)
- [x] Particle ID (ttbar and single particles)
- [x] dEdX (ttbar and single particles)
- [x] Tracking performances (ttbar and single muons)
- [x] Energy calibration (kaon0L, muons, photons)
- [x] MCInfo such parent-daughter relations, etc ... (one physics channel, e.g 1 TeV WW/ZZ->qqqq)
- [x] Background distributions (pure background simulations)
- [x] Event numbering after DST merge
- [x] LCFIPlus vertexing and flavour tagging

Please, post a comment or edit this comment to add a new entry or validate one entry as soon as we have the plots to validate it. Post also the plots to keep track of it.

**Comment by shaojunlu** [comment]
@rete I saw that you have the pure background simulations in the list. Could I use them in standard reconstruction to check the impact on the tracking efficiency? I may copy the ttbar simulation/reconstruction files into the ILD group folder, too.

**Comment by rete** [comment]
@shaojunlu I suggest we just check the tracking and jer/jes for the pre-release(s). For the release v01-19-06 the central production will be run and we will then go through this list.

**Comment by rete** [comment]
Hi all,
I have run the PID scripts available in the ILDPerformance package. I ran this on ttbar events (REC files) centrally produced from the 3rd test production available from : 

/ilc/prod/ilc/mc-opt-2/ild/rec/500-TDR_ws/6f_ttbar/ILD_l5_o1_v02/v01-19-06-p01/00009663/000/

After running the PID performance scripts I get the plots available there : 

[http://www.desy.de/~eteremi/3rd-test-prod/PID/](http://www.desy.de/~eteremi/3rd-test-prod/PID/)

Note that the plots (PIDs_pdg*.pdf) are produced by selecting particles with momentum > 3 GeV.

I found that : 
- the dEdX plot (input to the likelihood PID) seems reasonable compared to what was [presented by U. Einhaus](https://agenda.linearcollider.org/event/7906/contributions/41121/attachments/32884/50039/2018_03_21_SwAna_Coll_Meeting.pdf) a few weeks ago
- the [muon PID efficiency](http://www.desy.de/~eteremi/3rd-test-prod/PID/PIDs_pdg11_cut9.pdf) is really low as estimated by the final likelihood algorithm. In particular the efficiency seems really nice as estimated by PandoraPFA (BasicPID) and by the shower shape algorithms. For p > 3 GeV, the dEdX PID estimation starts to be bad but it seems to have a huge impact on the final PID...
- same comments for the [electrons efficiency](http://www.desy.de/~eteremi/3rd-test-prod/PID/PIDs_pdg11_cut9.pdf) as for muons: the efficiency is better with PandoraPFA and shower shape but worse for the final likelihood
- the [dEdX PID estimation for pions](http://www.desy.de/~eteremi/3rd-test-prod/PID/PIDs_pdg211_cut9.pdf) seems weird to me. From the [dEdX plot](http://www.desy.de/~eteremi/3rd-test-prod/PID/dEdx_plots_output.pdf) I understand that pions and muons are almost mixed and can't be separated in the region p > 3 GeV. I would have expected to have a pion PID with something like half muons / half pions which is not the case.

**Comment by rete** [comment]
## JER/JES performance

Dear all,
this is the performance plots from ILDPerformance run on uds samples for iLCSoft v01-19-06

- Jet energy resolution
![jer_05vs06](https://user-images.githubusercontent.com/950347/38310547-1ffaa704-381d-11e8-8925-9f225cde6b35.png)

- Jet energy scale and deviation from linearity
![jes_05vs06](https://user-images.githubusercontent.com/950347/38310564-31bed578-381d-11e8-9f0c-812dcbd57838.png)

This has already been [shown by Frank](https://agenda.linearcollider.org/event/7911/contributions/41142/attachments/32925/50119/gaede_sw_status_ildphone_20180403.pdf) during the last ILD phone meeting.

**Comment by danieljeans** [comment]
maps of simhits produced by muons uploaded to confluence:
https://confluence.desy.de/display/ILD/Simulation#Simulation-Validationofsimulation

no obvious drastic problems seen

**Comment by rete** [comment]
Hi Daniel,

> maps of simhits produced by muons uploaded to confluence:
> https://confluence.desy.de/display/ILD/Simulation#Simulation-Validationofsimulation

it seems the plots can't be seen on page. Even by clicking on them, the pictures are wrong.

**Comment by danieljeans** [comment]
when I click on it, I can download a ps file full of plots, as intended.

it's true that confluence doesn't seem to preview ps files.

**Comment by danieljeans** [comment]
detector material scans for latest version at http://research.kek.jp/people/jeans/ctpics/

no obvious problems noticed

**Comment by rete** [comment]
Everything has been checked so far. I close the issue. Thank you all !
