### ISSUE TITLE
Preparation for production at 250 GeV and 1 TeV 

### ISSUE THREAD

**Issue by rete** [iLCSoft/ILDConfig#86]
Here is summary of items to fulfill to make a Monte Carlo production at 250 GeV and 1 TeV feasible.

#### Simulation
- [x] Create the simulation models (final focusing)
- [x] LCIO input generator files available
- [x] Smearing position and sigma for interaction vertex and background vertexes
- [x] GineaPig ee pair and seeable pairs background files available
- [x] Gamma-gamma stdhep background files

### Reconstruction
- [x] Expected background events for each background type 
   - aa_lowpt  WW expected  number of events
   - aa_lowpt  WB expected  number of events
   - aa_lowpt  BW expected  number of events
   - aa_lowpt  BB expected  number of events
- [x] Beam sixe x,y,z
- [x] BeamCal background map for 3.5 T and 4 T variants available

#### Simulation
- [x] Create the simulation models (final focusing)
- [x] LCIO input generator files available
- [x] Smearing position and sigma for interaction vertex and background vertexes
- [x] GineaPig ee pair and seeable pairs background files available
- [x] Gamma-gamma stdhep background files

### Reconstruction
- [x] Expected background events for each background type 
   - aa_lowpt  WW expected  number of events
   - aa_lowpt  WB expected  number of events
   - aa_lowpt  BW expected  number of events
   - aa_lowpt  BB expected  number of events
- [x] Beam sixe x,y,z
- [x] BeamCal background map for 3.5 T and 4 T variants available

**Comment by JennyListDESY** [comment]
Hi Remi,
thanks for setting this up!

For the simulation step, I think we need as additional points 
* to create the detector models, at least the ones with the full field maps and the correct final focus strength
* to have the stdhep for the gammagamma -> lowpt hadrons

For the reconstruction, I'd suggest to make the item "expected background events" more specific and mention aa_lowpt hadrons explicitly. Furthermore we need
* standalone simulation of seeable pairs
* standalone simulation of  aa_lowpt hadrons
as prerequisites for reconstruction of physics events.

Finally, for 1 TeV, the three items for simulation are done as far as I understand, waiting only for the aa_lowpt hadron events from Tim and the creation of the special detector models.

**Comment by rete** [comment]
@JennyListDESY Thanks for the comment, I've updated the items.

@danieljeans From what I remember you have created the v03/v04/v05/v06 for 250 and 500 GeV, w and w/o antiDID. So the models for the 250 GeV are basically ready I believe (?). We need to create them also for the o2 option (see #85 ).
Also I remember that you use the 1 TeV model to extrapolate the final focusing magnet values for the 500 GeV (also 250 GeV ?). If so, can you create the models for the 1 TeV model w and w/o anti-DID field map ?

**Comment by akiyamiyamoto** [comment]
Hello, 

I guess that the list of process IDs and the number of events to be produced for 1 TeV is as follows.

Process name | process ID | Nb. events
--------------- | ----------- | -------------
vvxyyx | 35867 |50797
vvxyyx | 35868 |  9999
xxxxvv | 35911  | 9999
xxxxvv | 35912  | 10000
yyyyvv | 35935  | 10000
yyyyvv | 35936   | 9999

Is this correct ?

**Comment by JennyListDESY** [comment]
Hi Akiya,
Jakob will check the signal processIDs and event numbers, plus probably some of the most important backgrounds. However BEFORE we can think about the ee-physics events, what we need first is
* simulation of GuineaPig pairs for creating the BeamCal map
* simulation of the seeable pairs
* simulation of the aa_lowpt hadrons, which Tim uploaded to the grid last night

**Comment by rete** [comment]
@beyerja FYI

**Comment by danieljeans** [comment]
@rete 250 models are indeed ready:
v02 = prefect solenoid
v03 = sol. map + 250 quad fields
v04 = sol. map + 500 quad fields
v05 = sol. map + antiDID + 250 quad fields
v06 = sol. map + antiDID + 500 quad fields

however, I still suspect that these models with field maps do something strange, with low momentum particles getting stopped by G4 for no apparent reason...I hope to understand it out soon, but am struggling...

I guess a (recent) design for the 1 TeV final focus does not exist, and I never implemented one.
It may be reasonable to simply double the quadrupole field strengths with respect to 500 GeV...

**Comment by rete** [comment]
I have also added the beam size values x,y,z that are needed for the LCFIPlus vertexing.
We have the number of expected background events at 1 TeV for the four different types of backgrounds : 
- WW 0.526
- WB 0.634
- BW 0.634
- BB 0.744
I'm waiting for the beam size to update the steering file as they all are in the same file.

**Comment by danieljeans** [comment]
I checked the information I got from Okugi on Final Focus details.
He does include a design for 1 TeV, which has a ~doubled field strength in the final focus magnets compared to 500 GeV.
I will prepare a pull request with v7 and v8 models (without/with antiDID @ 1 TeV).
