### ISSUE TITLE
LCFIPlus weight/configuration files

### ISSUE THREAD

**Issue by ryonamin** [iLCSoft/ILDConfig#94]
For those who need the latest weight files for flavour taggigng with LCFIPlus(v00-07, https://github.com/lcfiplus/LCFIPlus/tree/v00-07),
the workiing examples below may help.
https://github.com/ryonamin/ILDConfig/tree/example20181219/LCFIPlusConfig

These were trained with the samples:
https://ild.ngt.ndu.ac.jp/elog/dbd-prod/239

**Comment by rete** [comment]
Hi Ryo,
Thanks for pointing out these resources. Can you make a pull request with the new weights please ?
Cheers

**Comment by ryonamin** [comment]
Hi Remi,
I hesitated a bit to integrate the weight files to the official repository now, because it is just a workaround for now, and even worse, I'm afraid it could cause a confusion/mistake. The weight files are supposed to be used with samples with re-vertexing with LCFIPlusv00-07(or later), and it doesn't make sense if one applys the weight files to the current default samples (without re-vertexing).
With the philosophy of keeping the official repository as clean as possible, personally I would wait to put them into the official repository until official sample-reproduction with the latest LCFIPlus has been done. 
What do you think?

**Comment by ryonamin** [comment]
Jenny has corrected me that there will be no official reprocessing for 500GeV. Sorry for my spam. I will prepare weight files and steering files for revertexing with (hopefully clear) instruction.

**Comment by rete** [comment]
Closed with PR #96
